//-----------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//   Changes to this file may cause incorrect behavior and will be lost if
//   the code is regenerated.
//
//   For more information, see: http://go.microsoft.com/fwlink/?LinkID=623246
// </auto-generated>
//-----------------------------------------------------------------------------
#pragma once

namespace com { namespace taulty { namespace LightControl {

public interface class ILightControlService
{
public:
    // Implement this function to handle calls to the GetBuildingDefinitionJson method.
    Windows::Foundation::IAsyncOperation<LightControlGetBuildingDefinitionJsonResult^>^ GetBuildingDefinitionJsonAsync(_In_ Windows::Devices::AllJoyn::AllJoynMessageInfo^ info );

    // Implement this function to handle calls to the SwitchBuilding method.
    Windows::Foundation::IAsyncOperation<LightControlSwitchBuildingResult^>^ SwitchBuildingAsync(_In_ Windows::Devices::AllJoyn::AllJoynMessageInfo^ info , _In_ bool interfaceMemberOnOff);

    // Implement this function to handle calls to the SwitchRoom method.
    Windows::Foundation::IAsyncOperation<LightControlSwitchRoomResult^>^ SwitchRoomAsync(_In_ Windows::Devices::AllJoyn::AllJoynMessageInfo^ info , _In_ Platform::String^ interfaceMemberRoomName, _In_ bool interfaceMemberOnOff);

    // Implement this function to handle calls to the ToggleRoomLight method.
    Windows::Foundation::IAsyncOperation<LightControlToggleRoomLightResult^>^ ToggleRoomLightAsync(_In_ Windows::Devices::AllJoyn::AllJoynMessageInfo^ info , _In_ Platform::String^ interfaceMemberRoomName, _In_ int32 interfaceMemberLightIndex);

};

} } } 
