//-----------------------------------------------------------------------------
// <auto-generated> 
//   This code was generated by a tool. 
// 
//   Changes to this file may cause incorrect behavior and will be lost if  
//   the code is regenerated.
//
//   Tool: AllJoynCodeGenerator.exe
//
//   This tool is located in the Windows 10 SDK and the Windows 10 AllJoyn 
//   Visual Studio Extension in the Visual Studio Gallery.  
//
//   The generated code should be packaged in a Windows 10 C++/CX Runtime  
//   Component which can be consumed in any UWP-supported language using 
//   APIs that are available in Windows.Devices.AllJoyn.
//
//   Using AllJoynCodeGenerator - Invoke the following command with a valid 
//   Introspection XML file and a writable output directory:
//     AllJoynCodeGenerator -i <INPUT XML FILE> -o <OUTPUT DIRECTORY>
// </auto-generated>
//-----------------------------------------------------------------------------
#pragma once

namespace com { namespace taulty { namespace LightControl {

// Methods
public ref class LightControlGetBuildingDefinitionJsonCalledEventArgs sealed
{
public:
    LightControlGetBuildingDefinitionJsonCalledEventArgs(_In_ Windows::Devices::AllJoyn::AllJoynMessageInfo^ info);

    property Windows::Devices::AllJoyn::AllJoynMessageInfo^ MessageInfo
    {
        Windows::Devices::AllJoyn::AllJoynMessageInfo^ get() { return m_messageInfo; }
    }

    property LightControlGetBuildingDefinitionJsonResult^ Result
    {
        LightControlGetBuildingDefinitionJsonResult^ get() { return m_result; }
        void set(_In_ LightControlGetBuildingDefinitionJsonResult^ value) { m_result = value; }
    }

    Windows::Foundation::Deferral^ GetDeferral();

    static Windows::Foundation::IAsyncOperation<LightControlGetBuildingDefinitionJsonResult^>^ GetResultAsync(LightControlGetBuildingDefinitionJsonCalledEventArgs^ args)
    {
        args->InvokeAllFinished();
        auto t = concurrency::create_task(args->m_tce);
        return concurrency::create_async([t]() -> concurrency::task<LightControlGetBuildingDefinitionJsonResult^>
        {
            return t;
        });
    }
    
private:
    void Complete();
    void InvokeAllFinished();
    void InvokeCompleteHandler();

    bool m_raised;
    int m_completionsRequired;
    concurrency::task_completion_event<LightControlGetBuildingDefinitionJsonResult^> m_tce;
    std::mutex m_lock;
    Windows::Devices::AllJoyn::AllJoynMessageInfo^ m_messageInfo;
    LightControlGetBuildingDefinitionJsonResult^ m_result;
};

public ref class LightControlSwitchBuildingCalledEventArgs sealed
{
public:
    LightControlSwitchBuildingCalledEventArgs(_In_ Windows::Devices::AllJoyn::AllJoynMessageInfo^ info, _In_ bool interfaceMemberOnOff);

    property Windows::Devices::AllJoyn::AllJoynMessageInfo^ MessageInfo
    {
        Windows::Devices::AllJoyn::AllJoynMessageInfo^ get() { return m_messageInfo; }
    }

    property LightControlSwitchBuildingResult^ Result
    {
        LightControlSwitchBuildingResult^ get() { return m_result; }
        void set(_In_ LightControlSwitchBuildingResult^ value) { m_result = value; }
    }

    property bool OnOff
    {
        bool get() { return m_interfaceMemberOnOff; }
    }

    Windows::Foundation::Deferral^ GetDeferral();

    static Windows::Foundation::IAsyncOperation<LightControlSwitchBuildingResult^>^ GetResultAsync(LightControlSwitchBuildingCalledEventArgs^ args)
    {
        args->InvokeAllFinished();
        auto t = concurrency::create_task(args->m_tce);
        return concurrency::create_async([t]() -> concurrency::task<LightControlSwitchBuildingResult^>
        {
            return t;
        });
    }
    
private:
    void Complete();
    void InvokeAllFinished();
    void InvokeCompleteHandler();

    bool m_raised;
    int m_completionsRequired;
    concurrency::task_completion_event<LightControlSwitchBuildingResult^> m_tce;
    std::mutex m_lock;
    Windows::Devices::AllJoyn::AllJoynMessageInfo^ m_messageInfo;
    LightControlSwitchBuildingResult^ m_result;
    bool m_interfaceMemberOnOff;
};

public ref class LightControlSwitchRoomCalledEventArgs sealed
{
public:
    LightControlSwitchRoomCalledEventArgs(_In_ Windows::Devices::AllJoyn::AllJoynMessageInfo^ info, _In_ Platform::String^ interfaceMemberRoomName, _In_ bool interfaceMemberOnOff);

    property Windows::Devices::AllJoyn::AllJoynMessageInfo^ MessageInfo
    {
        Windows::Devices::AllJoyn::AllJoynMessageInfo^ get() { return m_messageInfo; }
    }

    property LightControlSwitchRoomResult^ Result
    {
        LightControlSwitchRoomResult^ get() { return m_result; }
        void set(_In_ LightControlSwitchRoomResult^ value) { m_result = value; }
    }

    property Platform::String^ RoomName
    {
        Platform::String^ get() { return m_interfaceMemberRoomName; }
    }

    property bool OnOff
    {
        bool get() { return m_interfaceMemberOnOff; }
    }

    Windows::Foundation::Deferral^ GetDeferral();

    static Windows::Foundation::IAsyncOperation<LightControlSwitchRoomResult^>^ GetResultAsync(LightControlSwitchRoomCalledEventArgs^ args)
    {
        args->InvokeAllFinished();
        auto t = concurrency::create_task(args->m_tce);
        return concurrency::create_async([t]() -> concurrency::task<LightControlSwitchRoomResult^>
        {
            return t;
        });
    }
    
private:
    void Complete();
    void InvokeAllFinished();
    void InvokeCompleteHandler();

    bool m_raised;
    int m_completionsRequired;
    concurrency::task_completion_event<LightControlSwitchRoomResult^> m_tce;
    std::mutex m_lock;
    Windows::Devices::AllJoyn::AllJoynMessageInfo^ m_messageInfo;
    LightControlSwitchRoomResult^ m_result;
    Platform::String^ m_interfaceMemberRoomName;
    bool m_interfaceMemberOnOff;
};

public ref class LightControlToggleRoomLightCalledEventArgs sealed
{
public:
    LightControlToggleRoomLightCalledEventArgs(_In_ Windows::Devices::AllJoyn::AllJoynMessageInfo^ info, _In_ Platform::String^ interfaceMemberRoomName, _In_ int32 interfaceMemberLightIndex);

    property Windows::Devices::AllJoyn::AllJoynMessageInfo^ MessageInfo
    {
        Windows::Devices::AllJoyn::AllJoynMessageInfo^ get() { return m_messageInfo; }
    }

    property LightControlToggleRoomLightResult^ Result
    {
        LightControlToggleRoomLightResult^ get() { return m_result; }
        void set(_In_ LightControlToggleRoomLightResult^ value) { m_result = value; }
    }

    property Platform::String^ RoomName
    {
        Platform::String^ get() { return m_interfaceMemberRoomName; }
    }

    property int32 LightIndex
    {
        int32 get() { return m_interfaceMemberLightIndex; }
    }

    Windows::Foundation::Deferral^ GetDeferral();

    static Windows::Foundation::IAsyncOperation<LightControlToggleRoomLightResult^>^ GetResultAsync(LightControlToggleRoomLightCalledEventArgs^ args)
    {
        args->InvokeAllFinished();
        auto t = concurrency::create_task(args->m_tce);
        return concurrency::create_async([t]() -> concurrency::task<LightControlToggleRoomLightResult^>
        {
            return t;
        });
    }
    
private:
    void Complete();
    void InvokeAllFinished();
    void InvokeCompleteHandler();

    bool m_raised;
    int m_completionsRequired;
    concurrency::task_completion_event<LightControlToggleRoomLightResult^> m_tce;
    std::mutex m_lock;
    Windows::Devices::AllJoyn::AllJoynMessageInfo^ m_messageInfo;
    LightControlToggleRoomLightResult^ m_result;
    Platform::String^ m_interfaceMemberRoomName;
    int32 m_interfaceMemberLightIndex;
};

// Readable Properties
// Writable Properties
} } } 
